export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';

export const FETCH_PROFILE_SUCCES = 'FETCH_PROFILE_SUCCES';
export const FETCH_PROFILE_BEGIN = 'FETCH_PROFILE_BEGIN'
export const FETCH_PROFILE_ERROR = 'FETCH_PROFILE_ERROR'